name: Validate

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Install
        uses: ./.github/actions/install
      # - name: Run prettier
      #   run: yarn run format
      # - name: Check linter
      #   run: yarn run lint:eslint
      # - name: Run check types
      #   run: npm run check-types
      - name: Build the project
        run: bun run build
